kymkyj/AlgoStart

- kym/test.java
> [feat] 알고리즘 개인 폴더 생성

- kym/proSkillTree.java
> [feat] 프로그래머스 2단계 스킬트리 커밋

- mkkim/crossingTruck/Solution.java
- mkkim/skillTree/Solution.java
1주차 알고리즘 스터디 
스킬트리, 다리를 지나는 트럭 구현
> [feat] 스킬트리, 다리를 지나는 트럭

- seonhak/passing_truck(fail).java
- seonhak/passing_truck.java
- seonhak/skill_trees.java
> Add skill_trees solution

- kym/proSkillTree.java
- kym/proSosuSearch_sol.java
- kym/proTarget.java
[fix] 지난주 스킬트리 문제가 main에 반영안되어 추가
- 소수찾기 부분 순열 알고리즘을 잘 몰라서 블로그 찾아보고 이해하는 방향으로 진행
- 타겟넘버는 DFS 사용하여 풀이 접근
코딩인터뷰의 목차로 알고리즘 별도 공부 회의 필요할듯
> [feat] 타겟넘버/소수찾기 커밋

- mkkim/findPrime/Solution.java
- mkkim/findPrime/description.md
- mkkim/targetNumber/Solution.java
- mkkim/targetNumber/description.md
- 소수 찾기 : 순열 및 제곱근을 활용한 소수찾기
- 타겟 넘버 : DFS 및 재귀를 활용하여 타겟넘버 카운트 추출
> [feat] 소수 찾기 / 타겟 넘버

- kym/boj2798.java
> test commit

- kym/proPrinter_sol.java
- kym/proSkillDevelop.java
큐형태로 풀려고 했지만 location 유지해주는 부분에서 삽질하다가 꼬여버렸다.
처음에 왠지 우선순위 큐를 써야겠다라는 생각이 있었음 -> 풀이를 찾아보고 이해함
> [feat] 프로그래머스 프린터, 기능개발 커밋

- seonhak/fibonacci/Fibonacci.java
- seonhak/make_min_num/MakeMinMum.java
- seonhak/make_min_num/MakeMinNumTest.java
- seonhak/max_and_min/MaxMin.java
- seonhak/number_expression/NumberExpression.java
피보나치수, 최댓값과 최솟값, 최솟값만들기, 숫자의표현 풀이입니다.
> [feat] 피보나치수, 최댓값과 최솟값, 최솟값만들기, 숫자의표현

- mkkim/cache/CacheTest.java
- mkkim/newId/NewIDTest.java
신규아이디 :https://blog.naver.com/mkzzang0928/222353590104
캐시 : https://blog.naver.com/mkzzang0928/222353481974
> feat : 프로그래머스 캐시 신규아이디

- kym/proNewId.java
- kym/proOneCache.java
> [feat] 프로그래머스 1차캐시

- mkkim/backjoon/IronBarTest.java
- mkkim/backjoon/MakeOneTest.java
- mkkim/backjoon/VirusTest.java
- mkkim/backjoon/missingParenthesesTest.java
잃어버린 괄호 https://github.com/kymkyj/AlgoStart/blob/mkkim/mkkim/backjoon/IronBarTest.java 
바이러스 https://github.com/kymkyj/AlgoStart/blob/mkkim/mkkim/backjoon/VirusTest.java
1만들기 https://github.com/kymkyj/AlgoStart/blob/mkkim/mkkim/backjoon/MakeOneTest.java
쇠막대기 https://github.com/kymkyj/AlgoStart/blob/mkkim/mkkim/backjoon/IronBarTest.java
> [feat] 잃어버린 괄호 , 1만들기, 바이러스, 쇠막대기 

- kym/boj1463.java
- kym/boj1541.java
- kym/boj2606.java
- kym/infFeStick.java
1로만들기 - 다이나믹 프로그래밍인데 먼말인지 모르겠어서 다른사람 풀이보고 이해..
> [feat] 바이러스, 쇠막대기, 1로만들기, 잃어버린괄호 커밋

- seonhak/cache/Cache.java
- seonhak/cache/CacheTest.java
- seonhak/iron_bar/IronBar.java
- seonhak/lost_bracket/LostBracket.java
- seonhak/make_number_one/MakeNumberOne.java
- seonhak/recommend_new_id/RecommNewId.java
- seonhak/recommend_new_id/RecommNewIdTest.java
- seonhak/virus/Virus.java
[feat] 바이러스, 1로만들기, 잃어버린괄호, 쇠막대기 풀이
> [feat] 바이러스, 1로만들기, 잃어버린괄호, 쇠막대기 풀이

- mkkim/backjoon/ATMTest.java
- mkkim/backjoon/HideSeekTest.java
- mkkim/backjoon/OrganicCabbageTest.java
atm https://blog.naver.com/mkzzang0928/222373567124 
숨바꼭질 https://blog.naver.com/mkzzang0928/222373485417 
유기농 배추 https://blog.naver.com/mkzzang0928/222373388274 
DP https://blog.naver.com/mkzzang0928/222322268528
> Feat : ATM, 숨바꼭질, 유기농 배추

- kym/boj1012.java
- kym/boj11399.java
- kym/boj1697.java
유기농배추는 다시 한번 풀어봐야할 것 같습니다.
시간이 없어서 다급하게 하다보니까 꼬여서.. 한데까지 해서 올려놓겠습니다.
> [feat] 숨바꼭질, ATM, 유기농배추 커밋

- seonhak/ATM/ATM.java
- seonhak/ATM/ATM_Try.java
- seonhak/hide_seek/HideSeek.java
- seonhak/organic_cabbage/OrganicCabbage.java
> [feat] 유기농배추, 숨박꼭질, ATM

- seonhak/ATM/ATM.java
- seonhak/ATM/ATM_Try.java
- seonhak/hide_seek/HideSeek.java
- seonhak/no_look_hear/NoLookHear.java
- seonhak/organic_cabbage/OrganicCabbage.java
- seonhak/stock_invest/StockInvest.java
- seonhak/string_explosion/StringExplosion.java
- seonhak/tomato/Tomato.java
> [feat] 주식투자, 토마토, 듣보잡, 문자열 폭발

- kym/boj10809.java
- kym/boj11725.java
- kym/boj15653.java
- kym/boj15653_sol.java
이번문제 너무 어렵군여!
시간도 없어서 한문제 못풀었어요 흙..
> [feat] 트리부모찾기, 구슬 탈출4, 알파벳 찾기 커밋

- bmkim/baekjoon/boj10809.java
- bmkim/baekjoon/boj11725.java
- bmkim/baekjoon/boj15653.java
- bmkim/baekjoon/boj1991.java
이번꺼 너무 어려웠어요~~~~
그래서 답지봤어요~~
봐도 몰라요~~~
> [feat] 알파벳 찾기, 구슬 탈출4, 트리 순회, 트리의 부모 찾기

- seonhak/alphabet/Alphabet.java
- seonhak/marble_escape4/MarbleEscape4.java
- seonhak/search_parents_tree/SearchParentsTree.java
- seonhak/tree_traversal/TreeTraversal.java
> [feat] 알파벳 찾기, 트리의 부모 찾기, 트리 순회, 구슬 탈출4

- bmkim/baekjoon/boj11000.java
- bmkim/baekjoon/boj13305.java
- bmkim/baekjoon/boj16234.java
- bmkim/baekjoon/boj16918.java
> [feat] 강의실 배정, 주유소, 봄버맨, 인구 이동

- kym/boj11000.java
- kym/boj13305.java
- kym/boj16918.java
> [feat] 봄버맨, 주유소, 강의실배정 커밋

- seonhak/210704-안전영역, 구간합구하기5, 동전1, 단지번호붙이기/Coin1.java
- seonhak/210704-안전영역, 구간합구하기5, 동전1, 단지번호붙이기/ComplexNum.java
- seonhak/210704-안전영역, 구간합구하기5, 동전1, 단지번호붙이기/IntervalSum5.java
- seonhak/210704-안전영역, 구간합구하기5, 동전1, 단지번호붙이기/SafeZoneDfs.java
안전영역 dfs로 하려고했는데 뭔가 안되네요. 나중에 재도전할게요. 금요일날 시간이 없을꺼 같아 미리 올립니다. 수고요
> [feat] 안전영역, 구간합구하기5, 동전1, 단지번호붙이기

- yoojin/20210703/BaeminOne.java
- yoojin/20210703/BaeminThree.java
- yoojin/20210703/BaeminTwo.java
- yoojin/20210703/CountingAptComplex.java
- yoojin/20210703/PrefixSUmFIve.java
- yoojin/20210703/SafeZone_Bfs.java
- yoojin/20210703/SafeZone_Dfs.java
[feat] 배민 3문제/ 단지번호붙이기/구간합구하기5/안전영역
동전1은 점화식이 도저히 이해가 잘 안됩니다ㅠ
> [feat] 배민 3문제/ 단지번호붙이기/구간합구하기5/안전영역

- bmkim/baekjoon/boj2468.java
- bmkim/baekjoon/boj2667.java
> [feat] 안전 영역, 단지 번호 붙이기

- kym/boj11660.java
- kym/boj11660_sol.java
- kym/boj2293.java
- kym/boj2293_sol.java
- kym/boj2468_sol.java
- kym/boj2667.java
> [feat] 안전영역, 동전1, 단지번호붙이기, 구간합구하기5

- seonhak/210710-포도주 시식, 공주님을 구해라, 출석체크, 징검다리 건너기/AttendanceCheck.java
- seonhak/210710-포도주 시식, 공주님을 구해라, 출석체크, 징검다리 건너기/CrossingBridgeDfs.java
- seonhak/210710-포도주 시식, 공주님을 구해라, 출석체크, 징검다리 건너기/SavePrincess.java
- seonhak/210710-포도주 시식, 공주님을 구해라, 출석체크, 징검다리 건너기/WineTasting.java
> [feat] 포도주 시식, 공주님을 구해라, 출석체크, 징검다리 건너기

- yoojin/20210717/ContinuousSum_1912.java
- yoojin/20210717/babyShark_16236.java
> [feat] 아기상어/연속합

- seonhak/210717-공유기 설치, 아기상어, 연속합, 스티커/BabyShark.java
- seonhak/210717-공유기 설치, 아기상어, 연속합, 스티커/ConsecutiveSum.java
- seonhak/210717-공유기 설치, 아기상어, 연속합, 스티커/InstallWifi.java
- seonhak/210717-공유기 설치, 아기상어, 연속합, 스티커/Sticker.java
> [feat] 공유기설치, 아기상어, 연속합, 스티커

- kym/boj1912.java
- kym/boj2110.java
> [feat] 공유기설치, 연속합 커밋

- yoojin/20210724/StartLink_5014.java
- yoojin/20210724/WolfandSheep_16956.java
> [feat] 스타트링크 늑대와양

- seonhak/210724-늑대와 양, 스타트링크, 로봇청소기/RoboticVaccum.java
- seonhak/210724-늑대와 양, 스타트링크, 로봇청소기/StartLink.java
- seonhak/210724-늑대와 양, 스타트링크, 로봇청소기/WolfSheep.java
> [feat] 늑대와 양, 스타트링크, 로봇청소기

- kym/bojStartLink.java
- kym/bojStartLink_sol.java
- kym/bojWolfAndSheep.java
한데까지 커밋했습니다.. 
로봇청소기 아직 완료 못함..
> [feat] 늑대와양, 스타트링크 커밋

- kym/bojSevenNanJangE.java
- kym/bojSevenPrincess_sol.java
- kym/bojTournament.java
> [feat] 일곱난쟁이, 토너먼트, 소문난칠공주

- seonhak/210731-토너먼트, 일곱 난쟁이, 소문난 칠공주, 최소 스패닝 트리/FamousSevenPrincesses.java
- seonhak/210731-토너먼트, 일곱 난쟁이, 소문난 칠공주, 최소 스패닝 트리/MST.java
- seonhak/210731-토너먼트, 일곱 난쟁이, 소문난 칠공주, 최소 스패닝 트리/SevenDwarfs.java
- seonhak/210731-토너먼트, 일곱 난쟁이, 소문난 칠공주, 최소 스패닝 트리/Tournament.java
- seonhak/210807-타겟넘버,네트워크,체육복/GymSuit.java
- seonhak/210807-타겟넘버,네트워크,체육복/Network.java
- seonhak/210807-타겟넘버,네트워크,체육복/TargetNumber.java
- seonhak/210822-여행경로, 큰수만들기, 디스크컨트롤러/DiscoController.java
- seonhak/210822-여행경로, 큰수만들기, 디스크컨트롤러/MakeBigNumber.java
- seonhak/210822-여행경로, 큰수만들기, 디스크컨트롤러/TravelPath.java
> [feat] 여행경로, 큰수만들기, 디스크컨트롤러

- seonhak/210904-문자열 반복, 균현잡힌 세상, 카뱅 로봇공장/BalancedWorld.java
- seonhak/210904-문자열 반복, 균현잡힌 세상, 카뱅 로봇공장/RobotFactoryKakaoBank.java
- seonhak/210904-문자열 반복, 균현잡힌 세상, 카뱅 로봇공장/StringRepeat.java
- seonhak/210911-올리브영 최소한승경로/MinimunCrossingSubway.java
> [feat] 올리브영 최소환승경로

- yoojin/20210918/baekjoon_1743_20210918.java
- yoojin/20210918/baekjoon_7569_20210918.java
> feat 두문제,,

- seonhak/210918-음식물피하기, 달리기, 토마토/AvoidFood.java
- seonhak/210918-음식물피하기, 달리기, 토마토/Running.java
- seonhak/210918-음식물피하기, 달리기, 토마토/Tomato7569.java
> [feat] 음식물피하기, 달리기, 토마토

- kym/bojFoodAvoid.java
- kym/bojTomato.java
> [feat] 음식물피하기, 토마토 커밋

- seonhak/210925-로또, 제로, 다이얼/Dial.java
- seonhak/210925-로또, 제로, 다이얼/Lotto.java
- seonhak/210925-로또, 제로, 다이얼/Zero.java
> [feat] 로또, 제로, 다이얼
